#!/bin/bash
#$ -V
#$ -j y
#$ -N disordered_lattice_thrust
#$ -cwd
#$ -l cores=4,tesla_2070=3
#$ -t 1:10

thrust_exe=thrust_lorenz

# warming run
./${thrust_exe}

rm -f thrust_gpu_${SGE_TASK_ID}.dat

for ((a=16;a<=2048;a*=2)); do
    echo "$a"

    echo -n "$a " >> thrust_gpu_${SGE_TASK_ID}.dat
    /usr/bin/time -f %e -o thrust_gpu_${SGE_TASK_ID}.dat -a ./${thrust_exe} $a > /dev/null

    echo ""
done
