#!/bin/bash
#$ -V
#$ -j y
#$ -N phase_oscillator_3gpu
#$ -cwd
#$ -l cores=4,tesla_2070=3
#$ -t 1:10

vexcl_exe=vexcl_phase_oscillator

export OCL_PLATFORM=NVIDIA
export OCL_DEVICE=2070
export OCL_MAX_DEVICES=3

# warming runs
./${vexcl_exe}

rm -f vexcl_3gpu_${SGE_TASK_ID}.dat

for ((a=256;a<=4194304;a*=2)); do
    echo "$a "

    echo -n "$a " >> vexcl_3gpu_${SGE_TASK_ID}.dat
    /usr/bin/time -f %e -o vexcl_3gpu_${SGE_TASK_ID}.dat -a ./${vexcl_exe} $a > /dev/null

    echo ""
done
