#!/bin/bash
#$ -V
#$ -j y
#$ -N lorenz_ensemble_2gpu
#$ -cwd
#$ -l cores=4,tesla_2070=2
#$ -t 1:10

vexcl_exe=vexcl_lorenz

export OCL_PLATFORM=NVIDIA
export OCL_DEVICE=2070
export OCL_MAX_DEVICES=2

# warming runs
./${vexcl_exe}

rm -f vexcl_2gpu_${SGE_TASK_ID}.dat

for ((a=256;a<=4194304;a*=2)); do
    echo "$a "

    echo -n "$a " >> vexcl_2gpu_${SGE_TASK_ID}.dat
    /usr/bin/time -f %e -o vexcl_2gpu_${SGE_TASK_ID}.dat -a ./${vexcl_exe} $a > /dev/null

    echo ""
done
