#!/bin/bash
#$ -V
#$ -j y
#$ -N lorenz_ensemble_3gpu
#$ -cwd
#$ -l cores=4,tesla_2070=3
#$ -t 1:10

# Speed up cuda initialization on headless nodes.
nvidia-smi -l 2>&1 > /dev/null &
NVSMI_PID=$!

export OCL_PLATFORM=NVIDIA
export OCL_DEVICE=2070
export OCL_MAX_DEVICES=2

# warming runs
./vexcl_lorenz

rm -f vexcl_3gpu_${SGE_TASK_ID}.dat

for ((a=256;a<=4194304;a*=2)); do
    echo "$a "

    echo -n "$a " >> vexcl_3gpu_${SGE_TASK_ID}.dat
    /usr/bin/time -f %e -o vexcl_3gpu_${SGE_TASK_ID}.dat -a ./vexcl_lorenz $a > /dev/null

    echo ""
done

kill $NVSMI_PID
